export const GOVERNORATES = [
  'Alexandria',
  'Aswan',
  'Asyut',
  'Beheira',
  'Beni Suef',
  'Cairo',
  'Dakahlia',
  'Damietta',
  'Faiyum',
  'Gharbia',
  'Giza',
  'Ismailia',
  'Kafr El Sheikh',
  'Luxor',
  'Matruh',
  'Minya',
  'Monufia',
  'New Valley',
  'North Sinai',
  'Port Said',
  'Qalyubia',
  'Qena',
  'Red Sea',
  'Sharqia',
  'Sohag',
  'South Sinai',
  'Suez',
  'Outside Egypt',
]

export const COUNTRIES = [
  'Egypt',
  'United Arab Emirates',
  'Saudi Arabia',
  'United States',
  'United Kingdom',
  'Germany',
  'France',
  'Canada',
  'Australia',
  'Italy',
  'Spain',
  'Netherlands',
  'Switzerland',
  'Austria',
  'Belgium',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Ireland',
  'Portugal',
  'Greece',
  'Poland',
  'Czech Republic',
  'Romania',
  'Hungary',
  'Turkey',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'Jordan',
  'Lebanon',
  'Morocco',
  'Tunisia',
  'Algeria',
  'Libya',
  'Sudan',
  'Iraq',
  'Iran',
  'Pakistan',
  'India',
  'Bangladesh',
  'Malaysia',
  'Indonesia',
  'Singapore',
  'Thailand',
  'Vietnam',
  'Philippines',
  'Japan',
  'South Korea',
  'China',
  'Taiwan',
  'Hong Kong',
  'Brazil',
  'Mexico',
  'Argentina',
  'Colombia',
  'Chile',
  'Peru',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Ghana',
  'Tanzania',
  'Ethiopia',
  'Uganda',
  'New Zealand',
  'Russia',
  'Ukraine',
  'Kazakhstan',
  'Georgia',
  'Azerbaijan',
  'Armenia',
  'Serbia',
  'Croatia',
  'Slovenia',
  'Bulgaria',
  'Slovakia',
  'Lithuania',
  'Latvia',
  'Estonia',
  'Iceland',
  'Luxembourg',
  'Malta',
  'Cyprus',
  'Nepal',
  'Sri Lanka',
  'Myanmar',
  'Cambodia',
  'Laos',
  'Mongolia',
  'Fiji',
  'Other',
]

export const GAME_QUESTIONS = [
  {
    id: 1,
    difficulty: 'easy',
    question: 'The Great Pyramid of Giza was built for which Pharaoh?',
    options: [
      { id: 'a', label: 'A', text: 'Ramesses II' },
      { id: 'b', label: 'B', text: 'Khufu (Cheops)', correct: true },
      { id: 'c', label: 'C', text: 'Tutankhamun' },
      { id: 'd', label: 'D', text: 'Cleopatra' },
    ],
    reward: 50,
    fact: 'The Great Pyramid was built around 2560 BCE for Pharaoh Khufu (also known as Cheops). It is the oldest of the Seven Wonders of the Ancient World and the only one still largely intact.',
  },
  {
    id: 2,
    difficulty: 'medium',
    question: 'Approximately how tall is the Great Pyramid of Giza today?',
    options: [
      { id: 'a', label: 'A', text: '100 meters' },
      { id: 'b', label: 'B', text: '120 meters' },
      { id: 'c', label: 'C', text: '138 meters', correct: true },
      { id: 'd', label: 'D', text: '160 meters' },
    ],
    reward: 100,
    fact: 'The Great Pyramid originally stood at 146.6 meters tall. Today, due to erosion and the loss of its capstone, it measures approximately 138.8 meters.',
  },
  {
    id: 3,
    challenge: 'hard',
    question: 'Upload a photo of the Pyramids of Giza (your own photo or a saved one) to earn your bonus credits and prove you\'ve been there — or that you\'re ready to go!',
    type: 'upload',
    reward: 150,
  },
]

export const FORM_SECTIONS = [
  { id: 'governorates', label: 'Governorates Explorer' },
  { id: 'places', label: 'Places & Attractions' },
  { id: 'nightlife', label: 'Nightlife & Events' },
  { id: 'marketplace', label: 'Local Products Marketplace' },
  { id: 'game', label: 'The M360 Game' },
]
